### PR TITLE
base-patches-30: Allow work without wake_alarm capability

### PR DESCRIPTION
**Pull request by zvova7890**

### CODE REVIEW

**Review by aleasto — CHANGES_REQUESTED** [review]
Thank you for this!

We cannot just block the wake_alarm capability on the container because it would break waydroid for everybody until they update the system.img
So could this be made to not rely on EPERM?
For example how about just replacing the `_ALARM` timers in the `android_alarm_to_clockid` array with their non-ALARM versions?

**Comment by zvova7890** [comment]
I don't know, maybe someone needs it? Can we just drop alarm timers?

I think this is totally unneeded for regular user, but maybe for some strange configuration... As I can see suspend control is already removed, and alarm timers is not fully functional without suspend control.
It can be interesting to use waydroid in plain wayland compositor(weston for example) in fullscreen mode. It is like android x86, but under android we have fully functional regular linux environment. In that case would be nice to leave suspend/wakeup control for android.

Also we can do some property settings, that by default will disallow alarm timers, but can be force-allowed with settings.

**Comment by aleasto** [comment]
> I don't know, maybe someone needs it? Can we just drop alarm timers?

Yea just drop alarm timers.

**Comment by aleasto** [comment]
I also have this patch to block CAP_WAKE_ALARM from init instead of the LXC config, that should block alarms from native services that don't use AlarmManagerService

```diff
diff --git a/init/init.cpp b/init/init.cpp
index 1ee6e2c7a..687dd7db2 100644
--- a/init/init.cpp
+++ b/init/init.cpp
@@ -699,6 +699,9 @@ int SecondStageMain(int argc, char** argv) {
     InitKernelLogging(argv);
     LOG(INFO) << "init second stage started!";
 
+    // Waydroid should not interrupt the host from sleeping
+    cap_drop_bound(CAP_WAKE_ALARM);
+
     // Init should not crash because of a dependence on any other process, therefore we ignore
     // SIGPIPE and handle EPIPE at the call site directly.  Note that setting a signal to SIG_IGN
     // is inherited across exec, but custom signal handlers are not.  Since we do not want to
```

**Comment by aleasto** [comment]
I think i'll merge this as-is so that we can have some control in the future if needed

**Pull request merged**
